/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ejemplos.ejemplo1swing;

import java.util.ArrayList;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDate;
import java.util.LinkedList;
import java.util.Iterator;
import java.util.StringTokenizer;

/**
 *
 * @author DAM110
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private DefaultTableModel modeloTabla;
    private int idUsuarioLogueado;
    private Perfil perfil;
    private List<Prestamo> prestamos;
    private int prueba = 10;
    private PerfilDAOImp perfilDAO;
    private UsuarioDAOImp usuarioDAO;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        pantallaInicio.setVisible(true);
        inicioSesion.setVisible(false);
        registro.setVisible(false);
        modeloTabla = (DefaultTableModel) jTable1.getModel();
        perfilDAO = new PerfilDAOImp();
        usuarioDAO = new UsuarioDAOImp();
        prestamos = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pantallaInicio = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        iniciarSesion = new javax.swing.JButton();
        registrarse = new javax.swing.JButton();
        lblIcono = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        inicioSesion = new javax.swing.JPanel();
        entrar = new javax.swing.JButton();
        cuadroContraseña = new javax.swing.JPasswordField();
        cuadroTexto = new javax.swing.JTextField();
        username = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        textoInicioSesion = new javax.swing.JLabel();
        volver = new javax.swing.JButton();
        logoInicio = new javax.swing.JLabel();
        pantallaDatos = new javax.swing.JPanel();
        bienvenido = new javax.swing.JLabel();
        saldo = new javax.swing.JLabel();
        iban = new javax.swing.JLabel();
        opcionesUsuario = new javax.swing.JPanel();
        botonSolicitar = new javax.swing.JButton();
        botonConsultar = new javax.swing.JButton();
        botonLiquidar = new javax.swing.JButton();
        botonConsultarMov = new javax.swing.JButton();
        botonNominas = new javax.swing.JButton();
        logoOpciones = new javax.swing.JLabel();
        cerrarSesion = new javax.swing.JButton();
        botonPrestamo = new javax.swing.JButton();
        registro = new javax.swing.JPanel();
        panelDatos = new javax.swing.JPanel();
        DNI = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        apellidos = new javax.swing.JLabel();
        introDNI = new javax.swing.JTextField();
        introNombre = new javax.swing.JTextField();
        introApellidos = new javax.swing.JTextField();
        telefono = new javax.swing.JLabel();
        introTelefono = new javax.swing.JTextField();
        fecha = new javax.swing.JLabel();
        introFecha = new javax.swing.JFormattedTextField();
        domicilio = new javax.swing.JLabel();
        introDomicilio = new javax.swing.JTextField();
        localidad = new javax.swing.JLabel();
        introLocalidad = new javax.swing.JTextField();
        sexo = new javax.swing.JLabel();
        estadoCivil = new javax.swing.JLabel();
        introEstado = new javax.swing.JComboBox<>();
        introSexo = new javax.swing.JComboBox<>();
        estadoLaboral = new javax.swing.JLabel();
        introEstadoLaboral = new javax.swing.JComboBox<>();
        introUsuario = new javax.swing.JTextField();
        introContra = new javax.swing.JTextField();
        isPareja = new javax.swing.JCheckBox();
        introDNIpareja = new javax.swing.JTextField();
        enviar = new javax.swing.JButton();
        volver2 = new javax.swing.JButton();
        introduceDatos = new javax.swing.JLabel();
        logoRegistro = new javax.swing.JLabel();
        solicitarPrestamo = new javax.swing.JPanel();
        cantidad = new javax.swing.JLabel();
        prestamo = new javax.swing.JLabel();
        cuotas = new javax.swing.JLabel();
        volver3 = new javax.swing.JButton();
        introCantidadd = new javax.swing.JTextField();
        introCuotas = new javax.swing.JTextField();
        logoSolicitarPrestamo = new javax.swing.JLabel();
        consultarPrestamo = new javax.swing.JPanel();
        prestamoActual = new javax.swing.JLabel();
        logoConsultarPrestamo = new javax.swing.JLabel();
        volver4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        consultarMovimientosAdmin = new javax.swing.JPanel();
        consultarMovimientosEnunciado = new javax.swing.JLabel();
        logoConsultarMovimientos = new javax.swing.JLabel();
        volver5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableMov = new javax.swing.JTable();
        botonEliminar = new javax.swing.JButton();
        consultarMovimientosEnunciado1 = new javax.swing.JLabel();
        introCantidadd1 = new javax.swing.JTextField();
        entradaIdClienteMov = new javax.swing.JTextField();
        botonBuscarMovFiltro = new javax.swing.JButton();
        barraMenu = new javax.swing.JMenuBar();
        opciones = new javax.swing.JMenu();
        salir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ventana principal");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new java.awt.CardLayout());

        pantallaInicio.setBackground(new java.awt.Color(102, 204, 255));

        titulo.setBackground(new java.awt.Color(0, 255, 204));
        titulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("BETA BANK");

        iniciarSesion.setText("Iniciar sesion");
        iniciarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarSesionActionPerformed(evt);
            }
        });

        registrarse.setText("Registrarse");
        registrarse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarseActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/logo.jpg"))); // NOI18N

        javax.swing.GroupLayout pantallaInicioLayout = new javax.swing.GroupLayout(pantallaInicio);
        pantallaInicio.setLayout(pantallaInicioLayout);
        pantallaInicioLayout.setHorizontalGroup(
            pantallaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pantallaInicioLayout.createSequentialGroup()
                .addGroup(pantallaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pantallaInicioLayout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(iniciarSesion)
                        .addGap(18, 18, 18)
                        .addComponent(registrarse))
                    .addGroup(pantallaInicioLayout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(titulo)))
                .addContainerGap(208, Short.MAX_VALUE))
            .addGroup(pantallaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pantallaInicioLayout.createSequentialGroup()
                    .addGap(97, 97, 97)
                    .addComponent(lblIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(99, Short.MAX_VALUE)))
        );
        pantallaInicioLayout.setVerticalGroup(
            pantallaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pantallaInicioLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(pantallaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pantallaInicioLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pantallaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iniciarSesion)
                    .addComponent(registrarse))
                .addContainerGap(155, Short.MAX_VALUE))
            .addGroup(pantallaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pantallaInicioLayout.createSequentialGroup()
                    .addGap(55, 55, 55)
                    .addComponent(lblIcono, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                    .addGap(56, 56, 56)))
        );

        getContentPane().add(pantallaInicio, "card2");

        inicioSesion.setBackground(new java.awt.Color(102, 204, 255));

        entrar.setText("Entrar");
        entrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarActionPerformed(evt);
            }
        });

        cuadroTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuadroTextoActionPerformed(evt);
            }
        });

        username.setText("Nombre de usuario:");

        password.setText("Contraseña:");

        textoInicioSesion.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        textoInicioSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoInicioSesion.setText("INICIO DE SESION");

        volver.setText("Volver");
        volver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        logoInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/logo2.jpg"))); // NOI18N

        javax.swing.GroupLayout inicioSesionLayout = new javax.swing.GroupLayout(inicioSesion);
        inicioSesion.setLayout(inicioSesionLayout);
        inicioSesionLayout.setHorizontalGroup(
            inicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inicioSesionLayout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addGroup(inicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(inicioSesionLayout.createSequentialGroup()
                        .addGroup(inicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(username)
                            .addComponent(password))
                        .addGap(27, 27, 27)
                        .addGroup(inicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cuadroTexto, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(cuadroContraseña)))
                    .addGroup(inicioSesionLayout.createSequentialGroup()
                        .addComponent(entrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(volver)))
                .addContainerGap(247, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inicioSesionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(textoInicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(inicioSesionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoInicio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        inicioSesionLayout.setVerticalGroup(
            inicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inicioSesionLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(textoInicioSesion)
                .addGap(31, 31, 31)
                .addGroup(inicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuadroTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(username))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(inicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuadroContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password))
                .addGap(18, 18, 18)
                .addGroup(inicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entrar)
                    .addComponent(volver))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(logoInicio)
                .addContainerGap())
        );

        getContentPane().add(inicioSesion, "card3");

        pantallaDatos.setBackground(new java.awt.Color(0, 153, 204));

        bienvenido.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        bienvenido.setText("BIENVENIDO ");

        saldo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        saldo.setText("SALDO TOTAL: 1000000€");

        iban.setText("ES21 0000 0000 00 0000000000");

        opcionesUsuario.setBackground(new java.awt.Color(102, 204, 255));

        botonSolicitar.setText("SOLICITAR PRESTAMO");
        botonSolicitar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonSolicitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSolicitarActionPerformed(evt);
            }
        });

        botonConsultar.setText("CONSULTAR PRESTAMO");
        botonConsultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultarActionPerformed(evt);
            }
        });

        botonLiquidar.setText("LIQUIDAR PRESTAMO");
        botonLiquidar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonLiquidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLiquidarActionPerformed(evt);
            }
        });

        botonConsultarMov.setText("Consultar Movimientos");
        botonConsultarMov.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonConsultarMov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultarMovActionPerformed(evt);
            }
        });

        botonNominas.setText("AGREGAR NOMINAS");
        botonNominas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonNominas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNominasActionPerformed(evt);
            }
        });

        logoOpciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/logo2.jpg"))); // NOI18N

        cerrarSesion.setText("Cerrar sesion");
        cerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionActionPerformed(evt);
            }
        });

        botonPrestamo.setText("MODIFICAR PRESTAMO");
        botonPrestamo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPrestamoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout opcionesUsuarioLayout = new javax.swing.GroupLayout(opcionesUsuario);
        opcionesUsuario.setLayout(opcionesUsuarioLayout);
        opcionesUsuarioLayout.setHorizontalGroup(
            opcionesUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, opcionesUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(opcionesUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(opcionesUsuarioLayout.createSequentialGroup()
                        .addGroup(opcionesUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, opcionesUsuarioLayout.createSequentialGroup()
                                .addComponent(botonSolicitar)
                                .addGap(18, 18, 18)
                                .addComponent(botonConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(botonLiquidar))
                            .addGroup(opcionesUsuarioLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(cerrarSesion))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, opcionesUsuarioLayout.createSequentialGroup()
                                .addComponent(logoOpciones)
                                .addGap(0, 538, Short.MAX_VALUE)))
                        .addGap(31, 31, 31))
                    .addGroup(opcionesUsuarioLayout.createSequentialGroup()
                        .addComponent(botonConsultarMov)
                        .addGap(91, 91, 91)
                        .addComponent(botonPrestamo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonNominas)
                        .addGap(21, 21, 21))))
        );
        opcionesUsuarioLayout.setVerticalGroup(
            opcionesUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opcionesUsuarioLayout.createSequentialGroup()
                .addGroup(opcionesUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(opcionesUsuarioLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(opcionesUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonSolicitar)
                            .addComponent(botonConsultar)
                            .addComponent(botonLiquidar)))
                    .addGroup(opcionesUsuarioLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(opcionesUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonConsultarMov)
                            .addComponent(botonNominas)
                            .addComponent(botonPrestamo))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addComponent(cerrarSesion)
                .addGap(7, 7, 7)
                .addComponent(logoOpciones)
                .addContainerGap())
        );

        javax.swing.GroupLayout pantallaDatosLayout = new javax.swing.GroupLayout(pantallaDatos);
        pantallaDatos.setLayout(pantallaDatosLayout);
        pantallaDatosLayout.setHorizontalGroup(
            pantallaDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(opcionesUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pantallaDatosLayout.createSequentialGroup()
                .addGroup(pantallaDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pantallaDatosLayout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addGroup(pantallaDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pantallaDatosLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(iban))
                            .addComponent(saldo)))
                    .addGroup(pantallaDatosLayout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(bienvenido)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pantallaDatosLayout.setVerticalGroup(
            pantallaDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pantallaDatosLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(bienvenido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saldo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iban)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opcionesUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pantallaDatos, "card5");

        registro.setBackground(new java.awt.Color(102, 204, 255));

        panelDatos.setBackground(new java.awt.Color(102, 204, 255));

        DNI.setText("DNI:");

        nombre.setText("Nombre:");

        apellidos.setText("Apellidos:");

        introDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                introDNIActionPerformed(evt);
            }
        });

        introApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                introApellidosActionPerformed(evt);
            }
        });

        telefono.setText("Telefono:");

        fecha.setText("Fecha de nacimiento:");

        introFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        introFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                introFechaActionPerformed(evt);
            }
        });

        domicilio.setText("Domicilio:");

        introDomicilio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                introDomicilioActionPerformed(evt);
            }
        });

        localidad.setText("Localidad:");

        introLocalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                introLocalidadActionPerformed(evt);
            }
        });

        sexo.setText("Sexo:");

        estadoCivil.setText("Estado civil:");

        introEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Casado", "Soltero" }));

        introSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hombre", "Mujer", "Prefiero no decirlo" }));

        estadoLaboral.setText("Estado laboral:");

        introEstadoLaboral.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Empleado", "Desempleado", " " }));

        introUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                introUsuarioActionPerformed(evt);
            }
        });

        isPareja.setLabel("¿Cliente es pareja?");

        introDNIpareja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                introDNIparejaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDatosLayout = new javax.swing.GroupLayout(panelDatos);
        panelDatos.setLayout(panelDatosLayout);
        panelDatosLayout.setHorizontalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(telefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DNI, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(apellidos, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDatosLayout.createSequentialGroup()
                                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(introNombre)
                                    .addComponent(introApellidos, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(introContra)
                                    .addGroup(panelDatosLayout.createSequentialGroup()
                                        .addComponent(isPareja)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(panelDatosLayout.createSequentialGroup()
                                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelDatosLayout.createSequentialGroup()
                                        .addComponent(introDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(introUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelDatosLayout.createSequentialGroup()
                                        .addComponent(introTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(introDNIpareja, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addComponent(fecha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(introFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addComponent(sexo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(introSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addComponent(localidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(introLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addComponent(domicilio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(introDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addComponent(estadoCivil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(introEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addComponent(estadoLaboral)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(introEstadoLaboral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDatosLayout.setVerticalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DNI)
                    .addComponent(introDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(introUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre)
                    .addComponent(introNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(introContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apellidos)
                    .addComponent(introApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(isPareja))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefono)
                    .addComponent(introTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(introDNIpareja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fecha)
                    .addComponent(introFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(domicilio)
                    .addComponent(introDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(localidad)
                    .addComponent(introLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sexo)
                    .addComponent(introSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estadoCivil)
                    .addComponent(introEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estadoLaboral)
                    .addComponent(introEstadoLaboral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        enviar.setText("Enviar");
        enviar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarActionPerformed(evt);
            }
        });

        volver2.setText("Volver");
        volver2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        volver2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volver2ActionPerformed(evt);
            }
        });

        introduceDatos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        introduceDatos.setText("INTRODUCE TUS DATOS");

        logoRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/logo2.jpg"))); // NOI18N

        javax.swing.GroupLayout registroLayout = new javax.swing.GroupLayout(registro);
        registro.setLayout(registroLayout);
        registroLayout.setHorizontalGroup(
            registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registroLayout.createSequentialGroup()
                .addGroup(registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logoRegistro)
                        .addGap(141, 141, 141)
                        .addComponent(enviar)
                        .addGap(18, 18, 18)
                        .addComponent(volver2))
                    .addGroup(registroLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(panelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(registroLayout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(introduceDatos)))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        registroLayout.setVerticalGroup(
            registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registroLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(introduceDatos)
                .addGap(18, 18, 18)
                .addComponent(panelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enviar)
                    .addComponent(volver2))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoRegistro)
                .addContainerGap())
        );

        getContentPane().add(registro, "card3");

        solicitarPrestamo.setBackground(new java.awt.Color(102, 204, 255));

        cantidad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cantidad.setText("INTRODUCE LA CANTIDAD DE DINERO QUE QUIERES SOLICITAR:");

        prestamo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        prestamo.setText("PRESTAMO MAXIMO CONCEDIDO: 25000€ ");

        cuotas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cuotas.setText("NUMERO DE CUOTAS DE AMORTIZACION: ");

        volver3.setText("Volver");
        volver3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        volver3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volver3ActionPerformed(evt);
            }
        });

        introCantidadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                introCantidaddActionPerformed(evt);
            }
        });

        introCuotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                introCuotasActionPerformed(evt);
            }
        });

        logoSolicitarPrestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/logo2.jpg"))); // NOI18N

        javax.swing.GroupLayout solicitarPrestamoLayout = new javax.swing.GroupLayout(solicitarPrestamo);
        solicitarPrestamo.setLayout(solicitarPrestamoLayout);
        solicitarPrestamoLayout.setHorizontalGroup(
            solicitarPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(solicitarPrestamoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(solicitarPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(solicitarPrestamoLayout.createSequentialGroup()
                        .addGroup(solicitarPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(solicitarPrestamoLayout.createSequentialGroup()
                                .addComponent(cantidad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(introCantidadd, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(solicitarPrestamoLayout.createSequentialGroup()
                                .addComponent(cuotas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(introCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(102, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, solicitarPrestamoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(prestamo)
                        .addGap(158, 158, 158))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, solicitarPrestamoLayout.createSequentialGroup()
                        .addComponent(logoSolicitarPrestamo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(volver3)
                        .addGap(15, 15, 15))))
        );
        solicitarPrestamoLayout.setVerticalGroup(
            solicitarPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, solicitarPrestamoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(prestamo)
                .addGap(56, 56, 56)
                .addGroup(solicitarPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cantidad)
                    .addComponent(introCantidadd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(solicitarPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuotas)
                    .addComponent(introCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 224, Short.MAX_VALUE)
                .addComponent(volver3)
                .addGap(15, 15, 15))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, solicitarPrestamoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoSolicitarPrestamo)
                .addContainerGap())
        );

        getContentPane().add(solicitarPrestamo, "card6");

        consultarPrestamo.setBackground(new java.awt.Color(102, 204, 255));

        prestamoActual.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        prestamoActual.setText("SU PRESTAMO ACTUAL ES: ");

        logoConsultarPrestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/logo2.jpg"))); // NOI18N

        volver4.setText("Volver");
        volver4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        volver4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volver4ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout consultarPrestamoLayout = new javax.swing.GroupLayout(consultarPrestamo);
        consultarPrestamo.setLayout(consultarPrestamoLayout);
        consultarPrestamoLayout.setHorizontalGroup(
            consultarPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultarPrestamoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(consultarPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(consultarPrestamoLayout.createSequentialGroup()
                        .addComponent(prestamoActual)
                        .addGap(0, 439, Short.MAX_VALUE))
                    .addGroup(consultarPrestamoLayout.createSequentialGroup()
                        .addComponent(logoConsultarPrestamo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(volver4)))
                .addContainerGap())
            .addGroup(consultarPrestamoLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        consultarPrestamoLayout.setVerticalGroup(
            consultarPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, consultarPrestamoLayout.createSequentialGroup()
                .addGroup(consultarPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(consultarPrestamoLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(volver4))
                    .addGroup(consultarPrestamoLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(prestamoActual)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(logoConsultarPrestamo)))
                .addContainerGap())
        );

        getContentPane().add(consultarPrestamo, "card7");

        consultarMovimientosAdmin.setBackground(new java.awt.Color(102, 204, 255));

        consultarMovimientosEnunciado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        consultarMovimientosEnunciado.setText("Movimientos: ");

        logoConsultarMovimientos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/logo2.jpg"))); // NOI18N

        volver5.setText("Volver");
        volver5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        volver5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volver5ActionPerformed(evt);
            }
        });

        jTableMov.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableMov);

        botonEliminar.setText("Eliminar");
        botonEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });

        consultarMovimientosEnunciado1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        consultarMovimientosEnunciado1.setText("Id Cliente");

        entradaIdClienteMov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaIdClienteMovActionPerformed(evt);
            }
        });

        botonBuscarMovFiltro.setText("Buscar Por ID");
        botonBuscarMovFiltro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonBuscarMovFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarMovFiltroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout consultarMovimientosAdminLayout = new javax.swing.GroupLayout(consultarMovimientosAdmin);
        consultarMovimientosAdmin.setLayout(consultarMovimientosAdminLayout);
        consultarMovimientosAdminLayout.setHorizontalGroup(
            consultarMovimientosAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultarMovimientosAdminLayout.createSequentialGroup()
                .addGroup(consultarMovimientosAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(consultarMovimientosAdminLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(consultarMovimientosAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(consultarMovimientosAdminLayout.createSequentialGroup()
                                .addComponent(consultarMovimientosEnunciado)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(consultarMovimientosAdminLayout.createSequentialGroup()
                                .addComponent(logoConsultarMovimientos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(volver5))))
                    .addGroup(consultarMovimientosAdminLayout.createSequentialGroup()
                        .addGroup(consultarMovimientosAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(consultarMovimientosAdminLayout.createSequentialGroup()
                                .addGap(179, 179, 179)
                                .addComponent(consultarMovimientosEnunciado1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(entradaIdClienteMov, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(botonBuscarMovFiltro)
                                .addGap(221, 221, 221))
                            .addGroup(consultarMovimientosAdminLayout.createSequentialGroup()
                                .addGap(155, 155, 155)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(botonEliminar)))
                .addContainerGap())
            .addGroup(consultarMovimientosAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(consultarMovimientosAdminLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(introCantidadd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        consultarMovimientosAdminLayout.setVerticalGroup(
            consultarMovimientosAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, consultarMovimientosAdminLayout.createSequentialGroup()
                .addGroup(consultarMovimientosAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(consultarMovimientosAdminLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonEliminar)
                        .addGap(66, 66, 66)
                        .addComponent(volver5))
                    .addGroup(consultarMovimientosAdminLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(consultarMovimientosEnunciado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(consultarMovimientosAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(consultarMovimientosAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(entradaIdClienteMov)
                                .addComponent(botonBuscarMovFiltro))
                            .addComponent(consultarMovimientosEnunciado1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(logoConsultarMovimientos)))
                .addContainerGap())
            .addGroup(consultarMovimientosAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(consultarMovimientosAdminLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(introCantidadd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(consultarMovimientosAdmin, "card7");

        barraMenu.setBackground(new java.awt.Color(51, 204, 255));

        opciones.setText("Opciones");
        opciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        salir.setText("Salir");
        salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        opciones.add(salir);

        barraMenu.add(opciones);

        setJMenuBar(barraMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarSesionActionPerformed
        // TODO add your handling code here:
        pantallaInicio.setVisible(false);
        inicioSesion.setVisible(true);
        registro.setVisible(false);
        pantallaDatos.setVisible(false);

    }//GEN-LAST:event_iniciarSesionActionPerformed

    private void entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarActionPerformed
        // TODO add your handling code here:
        
        CuentaImp cuentaImp = new CuentaImp();
        List<Perfil> aux = new ArrayList();
        aux = perfilDAO.listar();
        JFrame errorlogin = new JFrame();
        boolean encontrado = false;
        for (Perfil perfil1 : aux) {

            if (perfil1.getUsuario().equalsIgnoreCase(cuadroTexto.getText()) && perfil1.getContrasena().equalsIgnoreCase(cuadroContraseña.getText())) {

                pantallaInicio.setVisible(false);
                inicioSesion.setVisible(false);
                registro.setVisible(false);
                pantallaDatos.setVisible(true);

                this.perfil = perfil1;
                
                Usuario usuario = usuarioDAO.porId(perfil.getIdPerfil());
                bienvenido.setText("Bienvenido " + usuario.getNombre());
                System.out.println("usuario " + usuario.getNombre());
                Cuenta cuenta = cuentaImp.porId(perfil1.getIdPerfil());

                saldo.setText("Saldo " + cuenta.getSaldo() + "€");
                iban.setText(cuenta.getIban());

                encontrado = true;
                Funciones.asignarID(usuario.getIdUsuario());

            }

        }
        if (!encontrado) {
            JOptionPane.showMessageDialog(errorlogin, "Usuario o contraseña Incorrecto");

        }

    }//GEN-LAST:event_entrarActionPerformed

    private void registrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarseActionPerformed
        // TODO add your handling code here:
        pantallaInicio.setVisible(false);
        inicioSesion.setVisible(false);
        registro.setVisible(true);
    }//GEN-LAST:event_registrarseActionPerformed

    private void cuadroTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuadroTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuadroTextoActionPerformed

    private void introDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_introDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_introDNIActionPerformed

    private void introFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_introFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_introFechaActionPerformed

    private void introDomicilioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_introDomicilioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_introDomicilioActionPerformed

    private void introLocalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_introLocalidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_introLocalidadActionPerformed

    private void enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarActionPerformed
        boolean cas;
        StringTokenizer st = new StringTokenizer(introFecha.getText(), "/");
        int dia = Integer.valueOf(st.nextToken());
        int mes = Integer.valueOf(st.nextToken());
        int anio = Integer.valueOf(st.nextToken());
        LocalDate fechaNac = LocalDate.of(anio, mes, dia);
        String x = introEstado.getSelectedItem().toString().toUpperCase();
        String val = introSexo.getSelectedItem().toString().toUpperCase();
        Sexo se = null;
        if (val.startsWith("H")) {
            se = Sexo.H;
        } else if (val.startsWith("M")) {
            se = Sexo.M;
        }
        EstadoCivil estCivil = EstadoCivil.valueOf(x);
        EstadoLaboral estLaboral = EstadoLaboral.valueOf(introEstadoLaboral.getSelectedItem().toString().toUpperCase());
        System.out.println(estCivil.toString());
        cas = estCivil.equals(EstadoCivil.CASADO);
        Perfil p1 = new Perfil(1, introUsuario.getText(), introContra.getText(), estCivil, estLaboral, false, TipoPerfilEnum.CLIENTE);
        perfilDAO.insertar(p1);
        p1.setIdPerfil(perfilDAO.porUsuario(p1.getUsuario()));
        int idP = 0;
        if (isPareja.isSelected()) {
            idP = usuarioDAO.porDNI(introDNIpareja.getText()).getIdUsuario();
        }
        Usuario c1 = new Usuario(1, p1, introDNI.getText(), introNombre.getText(), introApellidos.getText(), introTelefono.getText(), fechaNac, introDomicilio.getText(), introLocalidad.getText(), se, cas, 0.0, true, idP);
        usuarioDAO.insertar(c1);
        pantallaInicio.setVisible(false);
        inicioSesion.setVisible(false);
        registro.setVisible(false);
        pantallaDatos.setVisible(true);
    }//GEN-LAST:event_enviarActionPerformed

    private void volver2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volver2ActionPerformed
        // TODO add your handling code here:
        pantallaInicio.setVisible(true);
        inicioSesion.setVisible(false);
        registro.setVisible(false);
        pantallaDatos.setVisible(false);
    }//GEN-LAST:event_volver2ActionPerformed

    private void introApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_introApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_introApellidosActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        // TODO add your handling code here:
        pantallaInicio.setVisible(true);
        inicioSesion.setVisible(false);
        registro.setVisible(false);
        pantallaDatos.setVisible(false);
    }//GEN-LAST:event_volverActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void botonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultarActionPerformed
        // TODO add your handling code here:
        pantallaInicio.setVisible(false);
        inicioSesion.setVisible(false);
        registro.setVisible(false);
        pantallaDatos.setVisible(false);
        solicitarPrestamo.setVisible(false);

//        if(TipoPerfilEnum.CLIENTE.equals(this.perfil.getTipoPerfil())){
        consultarPrestamo.setVisible(true);
        rellenarTablaPrestamos(this.idUsuarioLogueado);
//        }
        // TODO 
//        else if (TipoPerfilEnum.BANQUERO.equals(this.perfil.getTipoPerfil())){
//            consultarUsuarios.setVisible(true);
//        }


    }//GEN-LAST:event_botonConsultarActionPerformed

    private void botonLiquidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLiquidarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonLiquidarActionPerformed

    private void botonSolicitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSolicitarActionPerformed
        // TODO add your handling code here:
        pantallaInicio.setVisible(false);
        inicioSesion.setVisible(false);
        registro.setVisible(false);
        pantallaDatos.setVisible(false);
        solicitarPrestamo.setVisible(true);
        // introCantidadd
        // introCuotas

        Usuario usuario = usuarioDAO.porId(idUsuarioLogueado);
        if (!perfil.isMoroso()) {
            if (EstadoLaboral.DESEMPLEADO.equals(this.perfil.getEstadolab()) || EstadoLaboral.ESTUDIANTE.equals(this.perfil.getEstadolab())) {
                if (usuario.isCasado() == true) {
                    if (usuario.getIdPareja()!=0) {
                        
                    }
                }
            }
        }


    }//GEN-LAST:event_botonSolicitarActionPerformed

    private void volver3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volver3ActionPerformed
        // TODO add your handling code here:
        pantallaInicio.setVisible(false);
        inicioSesion.setVisible(false);
        registro.setVisible(false);
        pantallaDatos.setVisible(true);
        solicitarPrestamo.setVisible(false);
    }//GEN-LAST:event_volver3ActionPerformed

    private void volver4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volver4ActionPerformed
        // TODO add your handling code here:
        pantallaInicio.setVisible(false);
        inicioSesion.setVisible(false);
        registro.setVisible(false);
        consultarPrestamo.setVisible(false);
        pantallaDatos.setVisible(true);
    }//GEN-LAST:event_volver4ActionPerformed

    private void cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionActionPerformed
        // TODO add your handling code here:
        pantallaInicio.setVisible(false);
        inicioSesion.setVisible(true);
        registro.setVisible(false);
        consultarPrestamo.setVisible(false);
        pantallaDatos.setVisible(false);
        cuadroTexto.setText("");
        cuadroContraseña.setText("");
    }//GEN-LAST:event_cerrarSesionActionPerformed

    private void introUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_introUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_introUsuarioActionPerformed

    private void introDNIparejaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_introDNIparejaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_introDNIparejaActionPerformed

    private void botonConsultarMovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultarMovActionPerformed
        // TODO add your handling code here:
        pantallaInicio.setVisible(false);
        inicioSesion.setVisible(false);
        registro.setVisible(false);
        consultarPrestamo.setVisible(false);
        pantallaDatos.setVisible(false);
        consultarMovimientosAdmin.setVisible(true);
        
         llenarTablaMovimientos(Funciones.IdusuarioLogieado());
         System.out.println("IdUsuario " + Funciones.IdusuarioLogieado());
        
    }//GEN-LAST:event_botonConsultarMovActionPerformed

    private void botonNominasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNominasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonNominasActionPerformed

    private void botonPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPrestamoActionPerformed
        // TODO add your handling code here:
        

    }//GEN-LAST:event_botonPrestamoActionPerformed

    private void volver5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volver5ActionPerformed
      pantallaInicio.setVisible(false);
        inicioSesion.setVisible(false);
        registro.setVisible(false);
        consultarPrestamo.setVisible(false);
        pantallaDatos.setVisible(true);
        consultarMovimientosAdmin.setVisible(false);  // TODO add your handling code here:
    }//GEN-LAST:event_volver5ActionPerformed

    
      private void llenarTablaMovimientos(int idusuario) { 
         
          ArrayList<Movimiento> datos= new ArrayList<>();  
        DefaultTableModel tabla =  new DefaultTableModel();
        UsuarioDAOImp usuarioDAOImp= new UsuarioDAOImp();
          System.out.println("La id de usuario es " + idusuario);
        
        Usuario aux=usuarioDAOImp.porId(idusuario);
        CuentaImp cuentaimp= new CuentaImp();
        Cuenta auxc= cuentaimp.porId(aux.getIdUsuario());
        System.out.println("numero de cuenta " + auxc.getIban() );
        MovCuentaImp movCuentaImp= new MovCuentaImp();
        ArrayList <MovCuenta> movimientos=movCuentaImp.listarPorCliente(auxc.getIban());
         
          for (MovCuenta movimiento : movimientos) {
              System.out.println("Movimiento " + movimiento.toString());
               MovimientoDAOImp mov = new  MovimientoDAOImp();
               datos.add(mov.porId(movimiento.getIdMovCuenta()));
               
          }
          
          
       
      
         
       String[] fila = new String[5];
        tabla.addColumn("IDMOV");
        tabla.addColumn("Cantidad");
        tabla.addColumn("Concepto");
        tabla.addColumn("Emisor");
        tabla.addColumn("Destinatario");
       
         
        
        
            
           
        for(int f=0; f<datos.size();f++){
            fila[0] = String.valueOf(datos.get(f).getIdMovimiento());
            fila[1] = String.valueOf(datos.get(f).getCantidad());
            fila[2] = datos.get(f).getConcepto();
            fila[3] = datos.get(f).getEmisor();
             fila[4] = datos.get(f).getDestinatario();
            tabla.addRow(fila);
        
         
  
        jTableMov.setModel(tabla);
    }
      }
      
          private int seleccionFila;

          //obtenemos el número de fila seleccionada al dar click en la tabla
    private int tuTablaMouseClicked(java.awt.event.MouseEvent evt) {                                     
        seleccionFila= jTableMov.rowAtPoint(evt.getPoint());
         MovimientoDAOImp mov = new  MovimientoDAOImp();
         mov.eliminar(seleccionFila);
        System.out.println("se ha eliminado"+seleccionFila);
        return seleccionFila;
    } 

    // evento al dar click en el boton agregar usuario
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {                                          
        //creamos variable locales para obtener los valores de cada columna de la fila seleccionada       
        int id=Integer.parseInt(String.valueOf(jTableMov.getValueAt(seleccionFila, 0)));
        String nombre=String.valueOf(jTableMov.getValueAt(seleccionFila, 1));
        String apellido1=String.valueOf(jTableMov.getValueAt(seleccionFila, 2));
        String apellido2=String.valueOf(jTableMov.getValueAt(seleccionFila, 3));
        String tipoPrestamo=String.valueOf(jTableMov.getValueAt(seleccionFila, 4));
        
        /*
         Agregas el código para guardar en el archivo, según la descripción de tu problema 
         sabes como realizarlo
        */
        System.out.println(id+nombre+apellido1);
    }
    
    
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:

    }//GEN-LAST:event_formWindowActivated

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        // TODO add your handling code here:
      MovimientoDAOImp mov = new  MovimientoDAOImp();
      mov.eliminar(seleccionFila+1);
      llenarTablaMovimientos(0);
      
       
    }//GEN-LAST:event_botonEliminarActionPerformed

    private void introCuotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_introCuotasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_introCuotasActionPerformed

    private void introCantidaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_introCantidaddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_introCantidaddActionPerformed

    private void entradaIdClienteMovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaIdClienteMovActionPerformed
        // TODO add your handling code here:
        entradaIdClienteMov.setText("Todos");
        
        
    }//GEN-LAST:event_entradaIdClienteMovActionPerformed

    private void botonBuscarMovFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarMovFiltroActionPerformed
        // TODO add your handling code here:
        entradaIdClienteMov.getText();
        if(entradaIdClienteMov.getText().equalsIgnoreCase("TODOS")){
            llenarTablaMovimientos(0);
        }
        else{
            llenarTablaMovimientos(Integer.parseInt(entradaIdClienteMov.getText()));
        }
    }//GEN-LAST:event_botonBuscarMovFiltroActionPerformed

    private void rellenarTablaPrestamos(int idUsuarioPrestamos) {
        try {
            // llamada a bd para traer los prestamos del usuaro idUsuario
            PrestamoDAOImp prestamoDAO = new PrestamoDAOImp();
            List<Prestamo> list = prestamoDAO.listarPorIdUsuario(idUsuarioPrestamos);

            String[] tituloColumnas = {"Prestamo", "Cliente", "Fecha Firma", "Cantidad", "Periodo en Meses", "Tipo de Interes", "Plazo en Dias", "Estado Prestamo", "Movimiento"};

            modeloTabla = new DefaultTableModel(null, tituloColumnas);
            jTable1.setModel(modeloTabla);

            for (Prestamo prestam : list) {
                String[] datosPrestamo = new String[tituloColumnas.length];
                int colum = 0;
                datosPrestamo[colum++] = String.valueOf(prestam.getIdPrestamo());
                datosPrestamo[colum++] = String.valueOf(prestam.getIdUsuario());
                datosPrestamo[colum++] = String.valueOf(prestam.getFechaFirma());
                datosPrestamo[colum++] = String.valueOf(prestam.getCantidad());
                datosPrestamo[colum++] = String.valueOf(prestam.getPeriodoMes());
                datosPrestamo[colum++] = String.valueOf(prestam.getTipoInteres());
                datosPrestamo[colum++] = String.valueOf(prestam.getPlazoDias());
                datosPrestamo[colum++] = String.valueOf(prestam.getEstadoPrest());
                datosPrestamo[colum++] = String.valueOf(prestam.getIdMovimiento());
                modeloTabla.addRow(datosPrestamo);
            }

        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }
    
    
//    if (!perfil.isMoroso()) {
//            if (EstadoLaboral.DESEMPLEADO.equals(this.perfil.getEstadolab()) || EstadoLaboral.ESTUDIANTE.equals(this.perfil.getEstadolab())) {
//                if (usuario.isCasado() == true) {
//                    if (usuario.getIdPareja()!=0) {
//                        
//                    }
//                }
//            }
//        }
    
    private boolean isValidoParaPrestamo(Usuario usuario){
        Perfil perfil = usuario.getPerfil();
        if(!perfil.isMoroso()){
            if(EstadoLaboral.ESTADOS_DEPNEDIENTE.contains(perfil.getEstadolab())){
                
            } else if(EstadoLaboral.ESTADOS_PRE_APROBADOS.contains(perfil.getEstadolab())){
                
            } else{
                // ES AUTONOMO ¿? ¿? ¿?
            }
        }
        return false;
    }
    
    private boolean comprobarCasados(Usuario usuario){
        if(usuario.isCasado() && usuario.getIdPareja() != 0){
            
        }
        
        return false;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DNI;
    private javax.swing.JLabel apellidos;
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JLabel bienvenido;
    private javax.swing.JButton botonBuscarMovFiltro;
    private javax.swing.JButton botonConsultar;
    private javax.swing.JButton botonConsultarMov;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonLiquidar;
    private javax.swing.JButton botonNominas;
    private javax.swing.JButton botonPrestamo;
    private javax.swing.JButton botonSolicitar;
    private javax.swing.JLabel cantidad;
    private javax.swing.JButton cerrarSesion;
    private javax.swing.JPanel consultarMovimientosAdmin;
    private javax.swing.JLabel consultarMovimientosEnunciado;
    private javax.swing.JLabel consultarMovimientosEnunciado1;
    private javax.swing.JPanel consultarPrestamo;
    private javax.swing.JPasswordField cuadroContraseña;
    private javax.swing.JTextField cuadroTexto;
    private javax.swing.JLabel cuotas;
    private javax.swing.JLabel domicilio;
    private javax.swing.JTextField entradaIdClienteMov;
    private javax.swing.JButton entrar;
    private javax.swing.JButton enviar;
    private javax.swing.JLabel estadoCivil;
    private javax.swing.JLabel estadoLaboral;
    private javax.swing.JLabel fecha;
    private javax.swing.JLabel iban;
    private javax.swing.JButton iniciarSesion;
    private javax.swing.JPanel inicioSesion;
    private javax.swing.JTextField introApellidos;
    private javax.swing.JTextField introCantidadd;
    private javax.swing.JTextField introCantidadd1;
    private javax.swing.JTextField introContra;
    private javax.swing.JTextField introCuotas;
    private javax.swing.JTextField introDNI;
    private javax.swing.JTextField introDNIpareja;
    private javax.swing.JTextField introDomicilio;
    private javax.swing.JComboBox<String> introEstado;
    private javax.swing.JComboBox<String> introEstadoLaboral;
    private javax.swing.JFormattedTextField introFecha;
    private javax.swing.JTextField introLocalidad;
    private javax.swing.JTextField introNombre;
    private javax.swing.JComboBox<String> introSexo;
    private javax.swing.JTextField introTelefono;
    private javax.swing.JTextField introUsuario;
    private javax.swing.JLabel introduceDatos;
    private javax.swing.JCheckBox isPareja;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableMov;
    private javax.swing.JLabel lblIcono;
    private javax.swing.JLabel localidad;
    private javax.swing.JLabel logoConsultarMovimientos;
    private javax.swing.JLabel logoConsultarPrestamo;
    private javax.swing.JLabel logoInicio;
    private javax.swing.JLabel logoOpciones;
    private javax.swing.JLabel logoRegistro;
    private javax.swing.JLabel logoSolicitarPrestamo;
    private javax.swing.JLabel nombre;
    private javax.swing.JMenu opciones;
    private javax.swing.JPanel opcionesUsuario;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JPanel pantallaDatos;
    private javax.swing.JPanel pantallaInicio;
    private javax.swing.JLabel password;
    private javax.swing.JLabel prestamo;
    private javax.swing.JLabel prestamoActual;
    private javax.swing.JButton registrarse;
    private javax.swing.JPanel registro;
    private javax.swing.JLabel saldo;
    private javax.swing.JMenuItem salir;
    private javax.swing.JLabel sexo;
    private javax.swing.JPanel solicitarPrestamo;
    private javax.swing.JLabel telefono;
    private javax.swing.JLabel textoInicioSesion;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel username;
    private javax.swing.JButton volver;
    private javax.swing.JButton volver2;
    private javax.swing.JButton volver3;
    private javax.swing.JButton volver4;
    private javax.swing.JButton volver5;
    // End of variables declaration//GEN-END:variables
}
