/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ejemplos.ejemplo1swing;

import java.util.ArrayList;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DAM110
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private DefaultTableModel modeloTabla;
    private int idUsuarioLogueado;
    private Perfil perfil;
    private List<Prestamo> prestamos = new ArrayList<>();
    private int prueba = 10;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        pantallaInicio.setVisible(true);
        inicioSesion.setVisible(false);
        registro.setVisible(false);
        modeloTabla = (DefaultTableModel) jTable1.getModel();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pantallaInicio = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        iniciarSesion = new javax.swing.JButton();
        registrarse = new javax.swing.JButton();
        lblIcono = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        inicioSesion = new javax.swing.JPanel();
        entrar = new javax.swing.JButton();
        cuadroContraseña = new javax.swing.JPasswordField();
        cuadroTexto = new javax.swing.JTextField();
        username = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        textoInicioSesion = new javax.swing.JLabel();
        volver = new javax.swing.JButton();
        logoInicio = new javax.swing.JLabel();
        pantallaDatos = new javax.swing.JPanel();
        bienvenido = new javax.swing.JLabel();
        saldo = new javax.swing.JLabel();
        iban = new javax.swing.JLabel();
        opcionesUsuario = new javax.swing.JPanel();
        botonSolicitar = new javax.swing.JButton();
        botonConsultar = new javax.swing.JButton();
        botonLiquidar = new javax.swing.JButton();
        botonModificar = new javax.swing.JButton();
        botonNominas = new javax.swing.JButton();
        logoOpciones = new javax.swing.JLabel();
        cerrarSesion = new javax.swing.JButton();
        registro = new javax.swing.JPanel();
        panelDatos = new javax.swing.JPanel();
        DNI = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        apellidos = new javax.swing.JLabel();
        introDNI = new javax.swing.JTextField();
        introNombre = new javax.swing.JTextField();
        introApellidos = new javax.swing.JTextField();
        telefono = new javax.swing.JLabel();
        introTelefono = new javax.swing.JTextField();
        fecha = new javax.swing.JLabel();
        introFecha = new javax.swing.JFormattedTextField();
        domicilio = new javax.swing.JLabel();
        introDomicilio = new javax.swing.JTextField();
        localidad = new javax.swing.JLabel();
        introLocalidad = new javax.swing.JTextField();
        sexo = new javax.swing.JLabel();
        estadoCivil = new javax.swing.JLabel();
        introEstado = new javax.swing.JComboBox<>();
        introSexo = new javax.swing.JComboBox<>();
        estadoLaboral = new javax.swing.JLabel();
        introEstadoLaboral = new javax.swing.JComboBox<>();
        enviar = new javax.swing.JButton();
        volver2 = new javax.swing.JButton();
        introduceDatos = new javax.swing.JLabel();
        logoRegistro = new javax.swing.JLabel();
        solicitarPrestamo = new javax.swing.JPanel();
        cantidad = new javax.swing.JLabel();
        prestamo = new javax.swing.JLabel();
        cuotas = new javax.swing.JLabel();
        volver3 = new javax.swing.JButton();
        introCantidadd = new javax.swing.JTextField();
        introCuotas = new javax.swing.JTextField();
        logoSolicitarPrestamo = new javax.swing.JLabel();
        consultarPrestamo = new javax.swing.JPanel();
        prestamoActual = new javax.swing.JLabel();
        logoConsultarPrestamo = new javax.swing.JLabel();
        volver4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        barraMenu = new javax.swing.JMenuBar();
        opciones = new javax.swing.JMenu();
        salir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ventana principal");
        getContentPane().setLayout(new java.awt.CardLayout());

        pantallaInicio.setBackground(new java.awt.Color(102, 204, 255));

        titulo.setBackground(new java.awt.Color(0, 255, 204));
        titulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("BETA BANK");

        iniciarSesion.setText("Iniciar sesion");
        iniciarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarSesionActionPerformed(evt);
            }
        });

        registrarse.setText("Registrarse");
        registrarse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarseActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/logo.jpg"))); // NOI18N

        javax.swing.GroupLayout pantallaInicioLayout = new javax.swing.GroupLayout(pantallaInicio);
        pantallaInicio.setLayout(pantallaInicioLayout);
        pantallaInicioLayout.setHorizontalGroup(
            pantallaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pantallaInicioLayout.createSequentialGroup()
                .addGroup(pantallaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pantallaInicioLayout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(iniciarSesion)
                        .addGap(18, 18, 18)
                        .addComponent(registrarse))
                    .addGroup(pantallaInicioLayout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(titulo)))
                .addContainerGap(208, Short.MAX_VALUE))
            .addGroup(pantallaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pantallaInicioLayout.createSequentialGroup()
                    .addGap(97, 97, 97)
                    .addComponent(lblIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(97, Short.MAX_VALUE)))
        );
        pantallaInicioLayout.setVerticalGroup(
            pantallaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pantallaInicioLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(pantallaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pantallaInicioLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pantallaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iniciarSesion)
                    .addComponent(registrarse))
                .addContainerGap(155, Short.MAX_VALUE))
            .addGroup(pantallaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pantallaInicioLayout.createSequentialGroup()
                    .addGap(55, 55, 55)
                    .addComponent(lblIcono, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                    .addGap(56, 56, 56)))
        );

        getContentPane().add(pantallaInicio, "card2");

        inicioSesion.setBackground(new java.awt.Color(102, 204, 255));

        entrar.setText("Entrar");
        entrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarActionPerformed(evt);
            }
        });

        cuadroTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuadroTextoActionPerformed(evt);
            }
        });

        username.setText("Nombre de usuario:");

        password.setText("Contraseña:");

        textoInicioSesion.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        textoInicioSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoInicioSesion.setText("INICIO DE SESION");

        volver.setText("Volver");
        volver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        logoInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/logo2.jpg"))); // NOI18N

        javax.swing.GroupLayout inicioSesionLayout = new javax.swing.GroupLayout(inicioSesion);
        inicioSesion.setLayout(inicioSesionLayout);
        inicioSesionLayout.setHorizontalGroup(
            inicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inicioSesionLayout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addGroup(inicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(inicioSesionLayout.createSequentialGroup()
                        .addGroup(inicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(username)
                            .addComponent(password))
                        .addGap(27, 27, 27)
                        .addGroup(inicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cuadroTexto, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(cuadroContraseña)))
                    .addGroup(inicioSesionLayout.createSequentialGroup()
                        .addComponent(entrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(volver)))
                .addContainerGap(247, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inicioSesionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(textoInicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(inicioSesionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoInicio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        inicioSesionLayout.setVerticalGroup(
            inicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inicioSesionLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(textoInicioSesion)
                .addGap(31, 31, 31)
                .addGroup(inicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuadroTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(username))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(inicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuadroContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password))
                .addGap(18, 18, 18)
                .addGroup(inicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entrar)
                    .addComponent(volver))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(logoInicio)
                .addContainerGap())
        );

        getContentPane().add(inicioSesion, "card3");

        pantallaDatos.setBackground(new java.awt.Color(0, 153, 204));

        bienvenido.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        bienvenido.setText("BIENVENIDO " + prueba);

        saldo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        saldo.setText("SALDO TOTAL: 1000000€");

        iban.setText("ES21 0000 0000 00 0000000000");

        opcionesUsuario.setBackground(new java.awt.Color(102, 204, 255));

        botonSolicitar.setText("SOLICITAR PRESTAMO");
        botonSolicitar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonSolicitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSolicitarActionPerformed(evt);
            }
        });

        botonConsultar.setText("CONSULTAR PRESTAMO");
        botonConsultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultarActionPerformed(evt);
            }
        });

        botonLiquidar.setText("LIQUIDAR PRESTAMO");
        botonLiquidar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonLiquidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLiquidarActionPerformed(evt);
            }
        });

        botonModificar.setText("MODIFICAR PRESTAMO");
        botonModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        botonNominas.setText("AGREGAR NOMINAS");
        botonNominas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        logoOpciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/logo2.jpg"))); // NOI18N

        cerrarSesion.setText("Cerrar sesion");
        cerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout opcionesUsuarioLayout = new javax.swing.GroupLayout(opcionesUsuario);
        opcionesUsuario.setLayout(opcionesUsuarioLayout);
        opcionesUsuarioLayout.setHorizontalGroup(
            opcionesUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opcionesUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(opcionesUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(opcionesUsuarioLayout.createSequentialGroup()
                        .addComponent(botonSolicitar)
                        .addGap(18, 18, 18)
                        .addComponent(botonConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(botonLiquidar)
                        .addContainerGap())
                    .addGroup(opcionesUsuarioLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(botonModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonNominas)
                        .addGap(87, 87, 87))
                    .addGroup(opcionesUsuarioLayout.createSequentialGroup()
                        .addComponent(logoOpciones)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, opcionesUsuarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cerrarSesion)
                .addGap(31, 31, 31))
        );
        opcionesUsuarioLayout.setVerticalGroup(
            opcionesUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opcionesUsuarioLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(opcionesUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonSolicitar)
                    .addComponent(botonConsultar)
                    .addComponent(botonLiquidar))
                .addGap(33, 33, 33)
                .addGroup(opcionesUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonModificar)
                    .addComponent(botonNominas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addComponent(cerrarSesion)
                .addGap(7, 7, 7)
                .addComponent(logoOpciones)
                .addContainerGap())
        );

        javax.swing.GroupLayout pantallaDatosLayout = new javax.swing.GroupLayout(pantallaDatos);
        pantallaDatos.setLayout(pantallaDatosLayout);
        pantallaDatosLayout.setHorizontalGroup(
            pantallaDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(opcionesUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pantallaDatosLayout.createSequentialGroup()
                .addGroup(pantallaDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pantallaDatosLayout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addGroup(pantallaDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pantallaDatosLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(iban))
                            .addComponent(saldo)))
                    .addGroup(pantallaDatosLayout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(bienvenido)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pantallaDatosLayout.setVerticalGroup(
            pantallaDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pantallaDatosLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(bienvenido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saldo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iban)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opcionesUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pantallaDatos, "card5");

        registro.setBackground(new java.awt.Color(102, 204, 255));

        panelDatos.setBackground(new java.awt.Color(102, 204, 255));

        DNI.setText("DNI:");

        nombre.setText("Nombre:");

        apellidos.setText("Apellidos:");

        introDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                introDNIActionPerformed(evt);
            }
        });

        introApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                introApellidosActionPerformed(evt);
            }
        });

        telefono.setText("Telefono:");

        fecha.setText("Fecha de nacimiento:");

        introFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        introFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                introFechaActionPerformed(evt);
            }
        });

        domicilio.setText("Domicilio:");

        introDomicilio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                introDomicilioActionPerformed(evt);
            }
        });

        localidad.setText("Localidad:");

        introLocalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                introLocalidadActionPerformed(evt);
            }
        });

        sexo.setText("Sexo:");

        estadoCivil.setText("Estado civil:");

        introEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Casado", "Soltero" }));

        introSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hombre", "Mujer", "Prefiero no decirlo" }));

        estadoLaboral.setText("Estado laboral:");

        introEstadoLaboral.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Empleado", "Desempleado", " " }));

        javax.swing.GroupLayout panelDatosLayout = new javax.swing.GroupLayout(panelDatos);
        panelDatos.setLayout(panelDatosLayout);
        panelDatosLayout.setHorizontalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(telefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DNI, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(apellidos, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(introDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(introNombre)
                                .addComponent(introApellidos, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE))
                            .addComponent(introTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addComponent(fecha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(introFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addComponent(sexo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(introSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addComponent(localidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(introLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addComponent(domicilio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(introDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addComponent(estadoCivil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(introEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addComponent(estadoLaboral)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(introEstadoLaboral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(195, Short.MAX_VALUE))
        );
        panelDatosLayout.setVerticalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DNI)
                    .addComponent(introDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre)
                    .addComponent(introNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apellidos)
                    .addComponent(introApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefono)
                    .addComponent(introTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fecha)
                    .addComponent(introFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(domicilio)
                    .addComponent(introDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(localidad)
                    .addComponent(introLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sexo)
                    .addComponent(introSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estadoCivil)
                    .addComponent(introEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estadoLaboral)
                    .addComponent(introEstadoLaboral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        enviar.setText("Enviar");
        enviar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarActionPerformed(evt);
            }
        });

        volver2.setText("Volver");
        volver2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        volver2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volver2ActionPerformed(evt);
            }
        });

        introduceDatos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        introduceDatos.setText("INTRODUCE TUS DATOS");

        logoRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/logo2.jpg"))); // NOI18N

        javax.swing.GroupLayout registroLayout = new javax.swing.GroupLayout(registro);
        registro.setLayout(registroLayout);
        registroLayout.setHorizontalGroup(
            registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registroLayout.createSequentialGroup()
                .addGroup(registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logoRegistro)
                        .addGap(141, 141, 141)
                        .addComponent(enviar)
                        .addGap(18, 18, 18)
                        .addComponent(volver2))
                    .addGroup(registroLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(panelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(registroLayout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(introduceDatos)))
                .addContainerGap(177, Short.MAX_VALUE))
        );
        registroLayout.setVerticalGroup(
            registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registroLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(introduceDatos)
                .addGap(18, 18, 18)
                .addComponent(panelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enviar)
                    .addComponent(volver2))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoRegistro)
                .addContainerGap())
        );

        getContentPane().add(registro, "card3");

        solicitarPrestamo.setBackground(new java.awt.Color(102, 204, 255));

        cantidad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cantidad.setText("INTRODUCE LA CANTIDAD DE DINERO QUE QUIERES SOLICITAR:");

        prestamo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        prestamo.setText("PRESTAMO MAXIMO CONCEDIDO: 25000€ ");

        cuotas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cuotas.setText("NUMERO DE CUOTAS DE AMORTIZACION: ");

        volver3.setText("Volver");
        volver3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        volver3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volver3ActionPerformed(evt);
            }
        });

        logoSolicitarPrestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/logo2.jpg"))); // NOI18N

        javax.swing.GroupLayout solicitarPrestamoLayout = new javax.swing.GroupLayout(solicitarPrestamo);
        solicitarPrestamo.setLayout(solicitarPrestamoLayout);
        solicitarPrestamoLayout.setHorizontalGroup(
            solicitarPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(solicitarPrestamoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(solicitarPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(solicitarPrestamoLayout.createSequentialGroup()
                        .addGroup(solicitarPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(solicitarPrestamoLayout.createSequentialGroup()
                                .addComponent(cantidad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(introCantidadd, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(solicitarPrestamoLayout.createSequentialGroup()
                                .addComponent(cuotas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(introCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(102, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, solicitarPrestamoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(prestamo)
                        .addGap(158, 158, 158))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, solicitarPrestamoLayout.createSequentialGroup()
                        .addComponent(logoSolicitarPrestamo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(volver3)
                        .addGap(15, 15, 15))))
        );
        solicitarPrestamoLayout.setVerticalGroup(
            solicitarPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, solicitarPrestamoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(prestamo)
                .addGap(56, 56, 56)
                .addGroup(solicitarPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cantidad)
                    .addComponent(introCantidadd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(solicitarPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuotas)
                    .addComponent(introCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 224, Short.MAX_VALUE)
                .addComponent(volver3)
                .addGap(15, 15, 15))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, solicitarPrestamoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoSolicitarPrestamo)
                .addContainerGap())
        );

        getContentPane().add(solicitarPrestamo, "card6");

        consultarPrestamo.setBackground(new java.awt.Color(102, 204, 255));

        prestamoActual.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        prestamoActual.setText("SU PRESTAMO ACTUAL ES: ");

        logoConsultarPrestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/logo2.jpg"))); // NOI18N

        volver4.setText("Volver");
        volver4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        volver4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volver4ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout consultarPrestamoLayout = new javax.swing.GroupLayout(consultarPrestamo);
        consultarPrestamo.setLayout(consultarPrestamoLayout);
        consultarPrestamoLayout.setHorizontalGroup(
            consultarPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultarPrestamoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(consultarPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(consultarPrestamoLayout.createSequentialGroup()
                        .addComponent(prestamoActual)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(consultarPrestamoLayout.createSequentialGroup()
                        .addComponent(logoConsultarPrestamo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(volver4)))
                .addContainerGap())
            .addGroup(consultarPrestamoLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(129, Short.MAX_VALUE))
        );
        consultarPrestamoLayout.setVerticalGroup(
            consultarPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, consultarPrestamoLayout.createSequentialGroup()
                .addGroup(consultarPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(consultarPrestamoLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(volver4))
                    .addGroup(consultarPrestamoLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(prestamoActual)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(logoConsultarPrestamo)))
                .addContainerGap())
        );

        getContentPane().add(consultarPrestamo, "card7");

        barraMenu.setBackground(new java.awt.Color(51, 204, 255));

        opciones.setText("Opciones");
        opciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        salir.setText("Salir");
        salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        opciones.add(salir);

        barraMenu.add(opciones);

        setJMenuBar(barraMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarSesionActionPerformed
        // TODO add your handling code here:
        pantallaInicio.setVisible(false);
        inicioSesion.setVisible(true);
        registro.setVisible(false);
        pantallaDatos.setVisible(false);

    }//GEN-LAST:event_iniciarSesionActionPerformed

    private void entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarActionPerformed
        // TODO add your handling code here:
        PerfilDAOImp perfilDAO = new PerfilDAOImp();
        UsuarioDAOImp usuarioDAO = new UsuarioDAOImp();
        CuentaImp cuentaImp = new CuentaImp();
        List<Perfil> aux = new ArrayList();
        aux = perfilDAO.listar();
        JFrame errorlogin = new JFrame();
        boolean encontrado = false;
        for (Perfil perfil1 : aux) {

            if (perfil1.getUsuario().equalsIgnoreCase(cuadroTexto.getText()) && perfil1.getContrasena().equalsIgnoreCase(cuadroContraseña.getText())) {

                pantallaInicio.setVisible(false);
                inicioSesion.setVisible(false);
                registro.setVisible(false);
                pantallaDatos.setVisible(true);

                this.perfil = perfil1;

                Usuario usuario = usuarioDAO.porId(perfil.getIdPerfil());
                bienvenido.setText("Bienvenido " + usuario.getNombre());
                System.out.println("usuario " + usuario.getNombre());
                Cuenta cuenta = cuentaImp.porId(perfil1.getIdPerfil());

                saldo.setText("Saldo " + cuenta.getSaldo() + "€");
                iban.setText(cuenta.getIban());

                encontrado = true;

            }

        }
        if (!encontrado) {
            JOptionPane.showMessageDialog(errorlogin, "Usuario o contraseña Incorrecto");
            
        }

    }//GEN-LAST:event_entrarActionPerformed

    private void registrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarseActionPerformed
        // TODO add your handling code here:
        pantallaInicio.setVisible(false);
        inicioSesion.setVisible(false);
        registro.setVisible(true);
    }//GEN-LAST:event_registrarseActionPerformed

    private void cuadroTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuadroTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuadroTextoActionPerformed

    private void introDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_introDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_introDNIActionPerformed

    private void introFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_introFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_introFechaActionPerformed

    private void introDomicilioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_introDomicilioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_introDomicilioActionPerformed

    private void introLocalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_introLocalidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_introLocalidadActionPerformed

    private void enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarActionPerformed
        // TODO add your handling code here:
        pantallaInicio.setVisible(false);
        inicioSesion.setVisible(false);
        registro.setVisible(false);
        pantallaDatos.setVisible(true);
    }//GEN-LAST:event_enviarActionPerformed

    private void volver2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volver2ActionPerformed
        // TODO add your handling code here:
        pantallaInicio.setVisible(true);
        inicioSesion.setVisible(false);
        registro.setVisible(false);
        pantallaDatos.setVisible(false);
    }//GEN-LAST:event_volver2ActionPerformed

    private void introApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_introApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_introApellidosActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        // TODO add your handling code here:
        pantallaInicio.setVisible(true);
        inicioSesion.setVisible(false);
        registro.setVisible(false);
        pantallaDatos.setVisible(false);
    }//GEN-LAST:event_volverActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void botonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultarActionPerformed
        // TODO add your handling code here:
        pantallaInicio.setVisible(false);
        inicioSesion.setVisible(false);
        registro.setVisible(false);
        pantallaDatos.setVisible(false);
        solicitarPrestamo.setVisible(false);

//        if(TipoPerfilEnum.CLIENTE.equals(this.perfil.getTipoPerfil())){
        consultarPrestamo.setVisible(true);
        rellenarTablaPrestamos(this.idUsuarioLogueado);
//        }
        // TODO 
//        else if (TipoPerfilEnum.BANQUERO.equals(this.perfil.getTipoPerfil())){
//            consultarUsuarios.setVisible(true);
//        }


    }//GEN-LAST:event_botonConsultarActionPerformed

    private void botonLiquidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLiquidarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonLiquidarActionPerformed

    private void botonSolicitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSolicitarActionPerformed
        // TODO add your handling code here:
        pantallaInicio.setVisible(false);
        inicioSesion.setVisible(false);
        registro.setVisible(false);
        pantallaDatos.setVisible(false);
        solicitarPrestamo.setVisible(true);
    }//GEN-LAST:event_botonSolicitarActionPerformed

    private void volver3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volver3ActionPerformed
        // TODO add your handling code here:
        pantallaInicio.setVisible(false);
        inicioSesion.setVisible(false);
        registro.setVisible(false);
        pantallaDatos.setVisible(true);
        solicitarPrestamo.setVisible(false);
    }//GEN-LAST:event_volver3ActionPerformed

    private void volver4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volver4ActionPerformed
        // TODO add your handling code here:
        pantallaInicio.setVisible(false);
        inicioSesion.setVisible(false);
        registro.setVisible(false);
        consultarPrestamo.setVisible(false);
        pantallaDatos.setVisible(true);
    }//GEN-LAST:event_volver4ActionPerformed

    private void cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionActionPerformed
        // TODO add your handling code here:
        pantallaInicio.setVisible(false);
        inicioSesion.setVisible(true);
        registro.setVisible(false);
        consultarPrestamo.setVisible(false);
        pantallaDatos.setVisible(false);
        cuadroTexto.setText("");
        cuadroContraseña.setText("");
    }//GEN-LAST:event_cerrarSesionActionPerformed

    private void rellenarTablaPrestamos(int idUsuarioPrestamos) {
        try {
            // llamada a bd para traer los prestamos del usuaro idUsuario
            PrestamoDAOImp prestamoDAO = new PrestamoDAOImp();
            List<Prestamo> list = prestamoDAO.listarPorIdUsuario(idUsuarioPrestamos);

            String[] tituloColumnas = {"Prestamo", "Cliente", "Fecha Firma", "Cantidad", "Periodo en Meses", "Tipo de Interes", "Plazo en Dias", "Estado Prestamo", "Movimiento"};
            Object[][] obj = null;

            for (int i = 0; i < list.size(); i++) {
                obj[i][0] = list.get(i).getIdPrestamo();
                obj[i][1] = list.get(i).getIdUsuario();
                obj[i][2] = list.get(i).getFechaFirma();
                obj[i][3] = list.get(i).getCantidad();
                obj[i][4] = list.get(i).getPeriodoMes();
                obj[i][5] = list.get(i).getTipoInteres();
                obj[i][6] = list.get(i).getPlazoDias();
                obj[i][7] = list.get(i).getEstadoPrest();
                obj[i][8] = list.get(i).getIdMovimiento();
            }

            modeloTabla = new DefaultTableModel(null, tituloColumnas);
            jTable1.setModel(modeloTabla);
            for (int i = 0; i < obj.length; i++) {
                modeloTabla.addRow(obj[i]);
            }

        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DNI;
    private javax.swing.JLabel apellidos;
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JLabel bienvenido;
    private javax.swing.JButton botonConsultar;
    private javax.swing.JButton botonLiquidar;
    private javax.swing.JButton botonModificar;
    private javax.swing.JButton botonNominas;
    private javax.swing.JButton botonSolicitar;
    private javax.swing.JLabel cantidad;
    private javax.swing.JButton cerrarSesion;
    private javax.swing.JPanel consultarPrestamo;
    private javax.swing.JPasswordField cuadroContraseña;
    private javax.swing.JTextField cuadroTexto;
    private javax.swing.JLabel cuotas;
    private javax.swing.JLabel domicilio;
    private javax.swing.JButton entrar;
    private javax.swing.JButton enviar;
    private javax.swing.JLabel estadoCivil;
    private javax.swing.JLabel estadoLaboral;
    private javax.swing.JLabel fecha;
    private javax.swing.JLabel iban;
    private javax.swing.JButton iniciarSesion;
    private javax.swing.JPanel inicioSesion;
    private javax.swing.JTextField introApellidos;
    private javax.swing.JTextField introCantidadd;
    private javax.swing.JTextField introCuotas;
    private javax.swing.JTextField introDNI;
    private javax.swing.JTextField introDomicilio;
    private javax.swing.JComboBox<String> introEstado;
    private javax.swing.JComboBox<String> introEstadoLaboral;
    private javax.swing.JFormattedTextField introFecha;
    private javax.swing.JTextField introLocalidad;
    private javax.swing.JTextField introNombre;
    private javax.swing.JComboBox<String> introSexo;
    private javax.swing.JTextField introTelefono;
    private javax.swing.JLabel introduceDatos;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblIcono;
    private javax.swing.JLabel localidad;
    private javax.swing.JLabel logoConsultarPrestamo;
    private javax.swing.JLabel logoInicio;
    private javax.swing.JLabel logoOpciones;
    private javax.swing.JLabel logoRegistro;
    private javax.swing.JLabel logoSolicitarPrestamo;
    private javax.swing.JLabel nombre;
    private javax.swing.JMenu opciones;
    private javax.swing.JPanel opcionesUsuario;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JPanel pantallaDatos;
    private javax.swing.JPanel pantallaInicio;
    private javax.swing.JLabel password;
    private javax.swing.JLabel prestamo;
    private javax.swing.JLabel prestamoActual;
    private javax.swing.JButton registrarse;
    private javax.swing.JPanel registro;
    private javax.swing.JLabel saldo;
    private javax.swing.JMenuItem salir;
    private javax.swing.JLabel sexo;
    private javax.swing.JPanel solicitarPrestamo;
    private javax.swing.JLabel telefono;
    private javax.swing.JLabel textoInicioSesion;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel username;
    private javax.swing.JButton volver;
    private javax.swing.JButton volver2;
    private javax.swing.JButton volver3;
    private javax.swing.JButton volver4;
    // End of variables declaration//GEN-END:variables
}
